config/routes.rb
Rails.application.routes.draw do
  root :to => 'twits#index'
  devise_for :users

  resources :twits
end

app/models/twit.rb
class Twit < ActiveRecord::Base
  validates :twit, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @twits = Twit.all
  end

  def show
    @twit = Twit.find(params[:id])
  end

  def new
    @twit = Twit.new
  end

  def create
    @twit = Twit.new(twit_params)
    if @twit.save
      flash[:notice] = 'YOU HAVE TWITTED SUCCESSFULLY!'
      redirect_to twits_path(@twit)
    else
      render :new
    end
  end

  def edit
    @twit = Twit.find(params[:id])
  end

  def update
    @twit = Twit.find(params[:id])
    if @twit.update(twit_params)
      flash[:notice] = "YOUR TWIT HAS BEEN UPDATED!!"
      redirect_to twit_path
    else
      render :edit
    end
  end

  def destroy
    @twit = Twit.find(params[:id])
    @twit.destroy
    flash[:alert] = "TWIT HAS BEEN DESTROYED!"
    redirect_to twits_path
  end

  private

    def twit_params
      params.require(:twit).permit(:twit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>YOU HAVE ERRORS!! FIX THEM!!!</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:alert] %>
<%= flash[:notice] %>

<div id="container">
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "SIGN UP", new_user_registration_path %> |
      <%= link_to "LOGIN", new_user_session_path %>
    <% end %>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/twits/_form.html.erb
<%= render 'layouts/errors', :object => @twit %>

<%= form_for @twit do |f| %>
  <%= f.label :twit %>
  <%= f.text_field :twit %>
  <%= f.submit %>
<% end %>

app/views/twits/edit.html.erb
<h1>EDIT YOUR TWIT!!</h1>

<%= render 'form' %>

app/views/twits/edit.js.erb
$('#edit_twit').hide().after('<%= j render("form") %>');

app/views/twits/index.html.erb
<h1>BITTER!!!!!!</h1>

<ul>
  <% @twits.each do |twit| %>
    <li><%= twit.twit %></li>
  <% end %>
</ul>

<h4><%= link_to "WRITE YOUR OWN TWIT!!", new_twit_path, id: "new_link" remote: true %></h4>

app/views/twits/new.html.erb
<h1>WRITE A NEW TWIT!!!!!!</h1>

<%= render 'form' %>

app/views/twits/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/twits/show.html.erb
<h1><%= @twit.twit %></h1>
<h6><%= @twit.created_at.to_s(:long) %></h6>

<p><%= link_to "EDIT TWIT!!", edit_twit_path, id: "edit_twit", remote: true %></p>
<p><%= link_to "DELETE TWIT!!", twit_path(@twit),
                                :data => { :confirm => "REALLY?!",
                                  :method => 'delete' } %></p>